window.STACK_SOURCES = {
  "cern-standard-model": {
    title: "CERN: The Standard Model",
    kind: "reference",
    url: "https://home.cern/science/physics/standard-model/",
    supports: "Standard Model framing, elementary particles, quarks, leptons, and force carriers.",
  },
  "pdg-compositeness": {
    title: "Particle Data Group: Quark and Lepton Compositeness",
    kind: "reference",
    url: "https://pdg.lbl.gov/2025/listings/rpp2025-list-quark-lepton-compositeness.pdf",
    supports: "High-energy search limits used as probe-scale anchors, not literal particle radii.",
  },
  "doe-quarks-gluons": {
    title: "DOE: Quarks and Gluons",
    kind: "reference",
    url: "https://www.energy.gov/science/doe-explainsquarks-and-gluons",
    supports: "Quarks, gluons, hadrons, confinement, and QCD caveats.",
  },
  "nist-electron-compton": {
    title: "NIST/CODATA: Reduced Electron Compton Wavelength",
    kind: "constant",
    url: "https://physics.nist.gov/cgi-bin/cuu/Value?ecomwlbar=",
    supports: "Quantum length reference; explicitly not an electron radius.",
  },
  "nist-proton-radius": {
    title: "NIST/CODATA: Proton RMS Charge Radius",
    kind: "constant",
    url: "https://physics.nist.gov/cgi-bin/cuu/Value?rp=",
    supports: "Femtometer-scale nucleon anchor.",
  },
  "nist-bohr-radius": {
    title: "NIST/CODATA: Bohr Radius",
    kind: "constant",
    url: "https://physics.nist.gov/cgi-bin/cuu/Value?bohrrada0=",
    supports: "Atomic-length scale anchor.",
  },
  "iupac-atom": {
    title: "IUPAC Gold Book: Atom",
    kind: "terminology",
    url: "https://goldbook.iupac.org/terms/view/A00493",
    supports: "Atom definition and element-characterizing particle framing.",
  },
  "iupac-atomic-number": {
    title: "IUPAC Gold Book: Atomic Number",
    kind: "terminology",
    url: "https://goldbook.iupac.org/terms/view/A00499/plain",
    supports: "Atomic number as proton count.",
  },
  "iupac-molecule": {
    title: "IUPAC Gold Book: Molecule",
    kind: "terminology",
    url: "https://goldbook.iupac.org/terms/view/M04002",
    supports: "Molecule definition.",
  },
  "iupac-macromolecule": {
    title: "IUPAC Gold Book: Macromolecule",
    kind: "terminology",
    url: "https://goldbook.iupac.org/terms/view/M03667",
    supports: "Macromolecule definition and repeating-unit framing.",
  },
  "iupac-polymer": {
    title: "IUPAC Gold Book: Polymer",
    kind: "terminology",
    url: "https://goldbook.iupac.org/terms/view/P04735",
    supports: "Polymer definition.",
  },
  "ncbi-protein-shapes": {
    title: "NCBI Bookshelf: Protein Shapes",
    kind: "biology",
    url: "https://www.ncbi.nlm.nih.gov/books/NBK26830/",
    supports: "Nanometer-scale biomolecular examples.",
  },
  "ncbi-membrane-structure": {
    title: "NCBI Bookshelf: Membrane Structure",
    kind: "biology",
    url: "https://www.ncbi.nlm.nih.gov/books/NBK21055/",
    supports: "Lipid bilayer and membrane-scale anchors.",
  },
  "ncbi-cell-composition": {
    title: "NCBI Bookshelf: Molecular Composition of Cells",
    kind: "biology",
    url: "https://www.ncbi.nlm.nih.gov/books/NBK9879/",
    supports: "Cells as organized molecular systems.",
  },
  "ncbi-bacterial-cell-size": {
    title: "NCBI Bookshelf: Origin and Evolution of Cells",
    kind: "biology",
    url: "https://www.ncbi.nlm.nih.gov/books/NBK9841/",
    supports: "Bacterial cell-size ranges.",
  },
  "ncbi-eukaryotic-cell-size": {
    title: "NCBI/PMC: Eukaryotic Cell Size Regulation",
    kind: "biology",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC11495193/",
    supports: "Wide eukaryotic cell-size variation.",
  },
  "ncbi-histology-cell": {
    title: "NCBI Bookshelf: Histology, Cell",
    kind: "biology",
    url: "https://www.ncbi.nlm.nih.gov/books/NBK554382/",
    supports: "Human cell examples, cell-count estimates, and brain-cell framing.",
  },
  "science-contract": {
    title: "Stack of Turtles: Physics Notes",
    kind: "project guardrail",
    url: "context/physics-notes.md",
    supports: "Careful wording where primary science does not settle a philosophical claim.",
  },
  "nasa-cosmic-history": {
    title: "NASA Science: Cosmic History",
    kind: "cosmology",
    url: "https://science.nasa.gov/universe/overview/",
    supports: "Approximate 13.8-billion-year universe-age frame.",
  },
  "esa-planck-age": {
    title: "ESA Planck: Almost Perfect Universe",
    kind: "cosmology",
    url: "https://www.esa.int/Science_Exploration/Space_Science/Planck/Planck_reveals_an_almost_perfect_Universe",
    supports: "Planck-derived universe age around 13.8 billion years.",
  },
};
